import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import * as fs from 'fs';import path from 'path';import {tmpdir} from 'os';import {randomUUID} from 'crypto';import {execFileSync} from 'child_process';
vi.mock('../db',()=>({db:{}}));
import {inventoryReviewArtifacts,readInventoryBytes} from '../services/lifecycleArtifactInventory';
import {diagnosticArtifactIO,validateReviewArtifacts,type ArtifactReview} from '../services/lifecycleArtifactValidation';
import {digest} from '../services/setLifecycleCore';import {maskBandFailure} from '../masking/maskBandLimit';
let root:string,row:ArtifactReview;const version='v4.6';const f=(suffix:string)=>path.join(root,`${row.card_id}_${version}.${suffix}`);
const inspect=()=>inventoryReviewArtifacts(row,root,version,maskBandFailure);
const snap=()=>fs.readdirSync(root).sort().map(n=>[n,digest(fs.readFileSync(path.join(root,n)))]);
function plan(value:unknown){const bytes=JSON.stringify(value);fs.writeFileSync(f('json'),bytes);row.plan_hash=digest(bytes);}
beforeEach(()=>{root=fs.mkdtempSync(path.join(tmpdir(),'artifact-inventory-'));row={card_id:randomUUID(),filename:null,plan_hash:null,preview_hash:digest('preview'),source_hash:digest('source')};row.filename=`${row.card_id}_${version}.jpg`;fs.writeFileSync(f('jpg'),'preview');fs.writeFileSync(f('lifecycle-source'),'source');plan({maskVersion:version,regions:[{yPct:90,hPct:10,xPct:0,wPct:100,type:'blur'}]});});
afterEach(()=>fs.rmSync(root,{recursive:true,force:true}));
describe('bounded independent inventory, actual filesystem and pure band validation',()=>{
 it('missing marker leaves original first-failure false, reads later matching bytes and changes nothing',()=>{const before=snap();const original=validateReviewArtifacts(row,root,version,maskBandFailure,()=>null,diagnosticArtifactIO(root,row.card_id,version).io);expect(original.category).toBe('missing_success_marker');expect(original.checks.plan.state).toBe('not_checked');const result=inspect();expect(result.checks.successMarker.state).toBe('missing');expect(result.checks.refusal.state).toBe('missing');for(const kind of ['plan','preview','source'])expect(result.checks[kind]).toMatchObject({state:'present',matches:true});expect(result.checks.plan.structure).toBe('accepted');expect(result).not.toHaveProperty('valid');expect(snap()).toEqual(before);});
 for(const [kind,suffix] of [['plan','json'],['preview','jpg'],['source','lifecycle-source']] as const){
  it(`${kind}: missing doesn't short-circuit the other files`,()=>{fs.rmSync(f(suffix));const r=inspect();expect(r.checks[kind].state).toBe('missing');expect(Object.keys(r.checks)).toHaveLength(5);expect(Object.entries(r.checks).filter(([k])=>!['successMarker','refusal',kind].includes(k)).every(([,v])=>v.state==='present')).toBe(true);});
  it(`${kind}: mutated hash is evidence only`,()=>{fs.writeFileSync(f(suffix),'RAW_FILE_SECRET');const r=inspect();expect(r.checks[kind].matches).toBe(false);expect(r.checks[kind].computedHash).toBe(digest('RAW_FILE_SECRET'));expect(JSON.stringify(r)).not.toContain('RAW_FILE_SECRET');});
  it(`${kind}: null/malformed saved hash doesn't match`,()=>{(row as any)[`${kind==='plan'?'plan':kind==='preview'?'preview':'source'}_hash`]='secret malformed value';const r=inspect();expect(r.checks[kind].storedHash).toBeNull();expect(r.checks[kind].matches).toBe(false);expect(JSON.stringify(r)).not.toContain('secret malformed');});
 }
 for(const suffix of ['json','jpg','lifecycle-source','ok','fail']){
  const kind=suffix==='json'?'plan':suffix==='jpg'?'preview':suffix==='lifecycle-source'?'source':suffix==='ok'?'successMarker':'refusal';
  it(`${suffix}: rejects FIFO promptly`,()=>{if(fs.existsSync(f(suffix)))fs.rmSync(f(suffix));execFileSync('mkfifo',[f(suffix)]);const start=Date.now();expect(inspect().checks[kind].state).toBe('unsafe');expect(Date.now()-start).toBeLessThan(1000);});
  it(`${suffix}: rejects directory and symlink`,()=>{if(fs.existsSync(f(suffix)))fs.rmSync(f(suffix));fs.mkdirSync(f(suffix));expect(inspect().checks[kind].state).toBe('unsafe');fs.rmSync(f(suffix),{recursive:true});fs.symlinkSync('/etc/passwd',f(suffix));expect(inspect().checks[kind].state).toBe('unsafe');});
  it(`${suffix}: rejects over limit before read`,()=>{if(!fs.existsSync(f(suffix)))fs.writeFileSync(f(suffix),'');fs.truncateSync(f(suffix),(suffix==='json'?2*1024*1024:['ok','fail'].includes(suffix)?64*1024:64*1024*1024)+1);expect(inspect().checks[kind].state).toBe('bounded');});
 }
 for(const filename of [null,'../other.jpg','/etc/passwd',`${randomUUID()}_${version}.jpg`,'bad_v4.6.jpg'])it(`rejects saved filename ${filename} before any file IO`,()=>{row.filename=filename;const read=vi.fn(()=>Buffer.alloc(0));const r=inventoryReviewArtifacts(row,root,version,maskBandFailure,read);expect(read).not.toHaveBeenCalled();expect(Object.values(r.checks).every(v=>v.state==='unsafe')).toBe(true);});
 it('rejects old-version filename',()=>{row.filename=`${row.card_id}_v3.jpg`;expect(inspect().checks.preview.state).toBe('unsafe');});
 it('reads exact rotated saved JPEG, not another existing rotation',()=>{row.filename=`${row.card_id}_${version}_r90.jpg`;fs.writeFileSync(path.join(root,row.filename),'rotated');row.preview_hash=digest('rotated');expect(inspect().checks.preview.matches).toBe(true);fs.rmSync(path.join(root,row.filename));expect(inspect().checks.preview.state).toBe('missing');});
 it('refusal content is not returned; empty/missing/current markers distinct',()=>{fs.writeFileSync(f('fail'),'RAW_REFUSAL_SECRET');fs.writeFileSync(f('ok'),'ok');expect(inspect().checks.refusal).toMatchObject({state:'present',nonempty:true});expect(inspect().checks.successMarker.state).toBe('present');expect(JSON.stringify(inspect())).not.toContain('RAW_REFUSAL_SECRET');fs.writeFileSync(f('fail'),' \n');expect(inspect().checks.refusal.nonempty).toBe(false);});
 const plans:[string,unknown,string][]=[['invalid JSON',null,'invalid_json'],['version',{maskVersion:'v0',regions:[{}]},'invalid_version'],['empty',{maskVersion:version,regions:[]},'invalid_regions'],['nonarray',{maskVersion:version,regions:{}},'invalid_regions'],['top oversized',{maskVersion:version,regions:[{yPct:0,hPct:36,wPct:100}]},'band_rejected'],['bottom oversized',{maskVersion:version,regions:[{yPct:44,hPct:56,wPct:100}]},'band_rejected'],['center',{maskVersion:version,regions:[{yPct:40,hPct:10,wPct:100}]},'band_rejected']];
 for(const [name,value,state] of plans)it(`plan ${name}`,()=>{if(name==='invalid JSON'){fs.writeFileSync(f('json'),'{');row.plan_hash=digest('{');}else plan(value);expect(inspect().checks.plan.structure).toBe(state);expect(inspect().checks.plan.matches).toBe(true);});
 it('a throwing structural validator does not mislabel successfully read bytes',()=>{const result=inventoryReviewArtifacts(row,root,version,()=>{throw new Error('PRIVATE_VALIDATOR');});expect(result.checks.plan.state).toBe('present');expect(result.checks.plan.structure).toBe('validation_unavailable');expect(result.checks.plan.matches).toBe(true);expect(JSON.stringify(result)).not.toContain('PRIVATE_VALIDATOR');});
 it('unreadable errors are redacted and independent',()=>{const read=(file:string,r:string,l:number)=>{if(file.endsWith('.jpg'))throw Object.assign(new Error('SECRET_PERMISSION_ERROR'),{code:'EACCES'});return readInventoryBytes(file,r,l);};const result=inventoryReviewArtifacts(row,root,version,maskBandFailure,read);expect(result.checks.preview.state).toBe('unreadable');expect(result.checks.source.matches).toBe(true);expect(JSON.stringify(result)).not.toContain('SECRET_PERMISSION_ERROR');});
});
describe('real file-race injection with bounded nonblocking descriptors',()=>{
 const readWith=(overrides:Partial<Parameters<typeof readInventoryBytes>[3]>)=>readInventoryBytes(f('jpg'),root,64*1024*1024,{...fs,...overrides});
 it('short read is detected and descriptor closed',()=>{let closed=0;expect(()=>readWith({readSync:((...args:any[])=>0) as any,closeSync:(fd)=>{closed++;fs.closeSync(fd);}})).toThrow();expect(closed).toBe(1);});
 it('growth during byte read is rejected without unbounded read',()=>{let changed=false;expect(()=>readWith({readSync:((...args:any[])=>{if(!changed){changed=true;fs.appendFileSync(f('jpg'),'MORE');}return (fs.readSync as any)(...args);}) as any})).toThrow();});
 it('same-size rewrite changes stat and is rejected',()=>{let changed=false;expect(()=>readWith({readSync:((...args:any[])=>{if(!changed){changed=true;fs.writeFileSync(f('jpg'),'changed');fs.utimesSync(f('jpg'),new Date(),new Date(Date.now()+1000));}return (fs.readSync as any)(...args);}) as any})).toThrow();});
 it('path replacement during read is detected even if old descriptor remains readable',()=>{let changed=false;expect(()=>readWith({readSync:((...args:any[])=>{if(!changed){changed=true;fs.renameSync(f('jpg'),f('old'));fs.writeFileSync(f('jpg'),'preview');}return (fs.readSync as any)(...args);}) as any})).toThrow();});
 it('path deletion after open is detected',()=>{let changed=false;expect(()=>readWith({readSync:((...args:any[])=>{if(!changed){changed=true;fs.unlinkSync(f('jpg'));}return (fs.readSync as any)(...args);}) as any})).toThrow();});
 it('regular path raced to FIFO before open never blocks and is rejected',()=>{expect(()=>readWith({openSync:((...args:any[])=>{fs.unlinkSync(f('jpg'));execFileSync('mkfifo',[f('jpg')]);return (fs.openSync as any)(...args);}) as any})).toThrow();});
 it('regular path raced to symlink before open is denied by O_NOFOLLOW',()=>{expect(()=>readWith({openSync:((...args:any[])=>{fs.unlinkSync(f('jpg'));fs.symlinkSync('/etc/passwd',f('jpg'));return (fs.openSync as any)(...args);}) as any})).toThrow();});
 it('inventory labels a raced read separately, without a partial hash',()=>{const read=(file:string,r:string,l:number)=>{if(file.endsWith('.jpg'))throw Object.assign(new Error('PRIVATE'),{code:'INVENTORY_CHANGED'});return readInventoryBytes(file,r,l);};const obs=inventoryReviewArtifacts(row,root,version,maskBandFailure,read).checks.preview;expect(obs.state).toBe('read_changed');expect(obs.computedHash).toBeUndefined();});
 it('rejects a directory escape before IO',()=>{expect(()=>readInventoryBytes('/etc/passwd',root,100)).toThrow();});
});
